# Generated by Django 5.1.15 on 2026-06-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('service', models.CharField(choices=[('Logistics', 'Logistics'), ('Car Hire', 'Car Hire'), ('Real Estate', 'Real Estate'), ('General Support', 'General Support')], max_length=80)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('source', models.CharField(blank=True, help_text='Page or component that originated this lead (e.g. /services/logistics).', max_length=120)),
                ('is_handled', models.BooleanField(default=False, help_text='Tick once a team member has responded to or actioned this lead.')),
                ('handled_notes', models.TextField(blank=True, help_text='Internal notes — outcome of follow-up, next steps, etc. Not visible to the customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'contact message',
                'verbose_name_plural': 'contact messages',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('service', models.CharField(choices=[('Logistics', 'Logistics'), ('Car Hire', 'Car Hire'), ('Real Estate', 'Real Estate'), ('General Support', 'General Support')], max_length=80)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('source', models.CharField(blank=True, help_text='Page or component that originated this lead (e.g. /services/logistics).', max_length=120)),
                ('is_handled', models.BooleanField(default=False, help_text='Tick once a team member has responded to or actioned this lead.')),
                ('handled_notes', models.TextField(blank=True, help_text='Internal notes — outcome of follow-up, next steps, etc. Not visible to the customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(blank=True, max_length=180)),
                ('destination', models.CharField(blank=True, max_length=180)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('cargo_or_need', models.CharField(blank=True, help_text='Cargo description, vehicle type, property type — whatever the visitor selected.', max_length=240)),
            ],
            options={
                'verbose_name': 'quote request',
                'verbose_name_plural': 'quote requests',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
