# Generated by Django 5.1.15 on 2026-07-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('service', models.CharField(choices=[('Logistics', 'Logistics'), ('Car Hire', 'Car Hire'), ('Real Estate', 'Real Estate'), ('General Support', 'General Support')], max_length=80)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('source', models.CharField(blank=True, help_text='Page or component that originated this lead (e.g. /services/logistics).', max_length=120)),
                ('is_handled', models.BooleanField(default=False, help_text='Tick once a team member has responded to or actioned this lead.')),
                ('handled_notes', models.TextField(blank=True, help_text='Internal notes — outcome of follow-up, next steps, etc. Not visible to the customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'contact message',
                'verbose_name_plural': 'contact messages',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'quote number sequence',
                'verbose_name_plural': 'quote number sequences',
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('service', models.CharField(choices=[('Logistics', 'Logistics'), ('Car Hire', 'Car Hire'), ('Real Estate', 'Real Estate'), ('General Support', 'General Support')], max_length=80)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('source', models.CharField(blank=True, help_text='Page or component that originated this lead (e.g. /services/logistics).', max_length=120)),
                ('is_handled', models.BooleanField(default=False, help_text='Tick once a team member has responded to or actioned this lead.')),
                ('handled_notes', models.TextField(blank=True, help_text='Internal notes — outcome of follow-up, next steps, etc. Not visible to the customer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_number', models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated reference code, e.g. NGW-2026-00042.', max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'quote request',
                'verbose_name_plural': 'quote requests',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogisticsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, help_text='Sub-category the visitor selected, e.g. "Long Haulage", "Self Drive".', max_length=80)),
                ('origin', models.CharField(blank=True, max_length=180)),
                ('destination', models.CharField(blank=True, max_length=180)),
                ('cargo_type', models.CharField(blank=True, max_length=180)),
                ('cargo_weight', models.CharField(blank=True, help_text='Free-text estimate, e.g. "2 tonnes", "500kg", "unknown".', max_length=80)),
                ('preferred_date', models.DateField(blank=True, help_text='Preferred pickup date.', null=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logistics_detail', to='leads.quoterequest')),
            ],
            options={
                'verbose_name': 'logistics detail',
                'verbose_name_plural': 'logistics details',
            },
        ),
        migrations.CreateModel(
            name='CarHireDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, help_text='Sub-category the visitor selected, e.g. "Long Haulage", "Self Drive".', max_length=80)),
                ('vehicle_type', models.CharField(blank=True, max_length=120)),
                ('pickup_location', models.CharField(blank=True, max_length=180)),
                ('return_location', models.CharField(blank=True, max_length=180)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('passengers', models.CharField(blank=True, help_text='Free-text count, e.g. "1", "4", "12", "staff team".', max_length=80)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car_hire_detail', to='leads.quoterequest')),
            ],
            options={
                'verbose_name': 'car hire detail',
                'verbose_name_plural': 'car hire details',
            },
        ),
        migrations.CreateModel(
            name='RealEstateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(blank=True, help_text='Sub-category the visitor selected, e.g. "Long Haulage", "Self Drive".', max_length=80)),
                ('property_type', models.CharField(blank=True, max_length=120)),
                ('preferred_area', models.CharField(blank=True, max_length=180)),
                ('bedrooms', models.CharField(blank=True, max_length=40)),
                ('budget', models.CharField(blank=True, help_text='Free-text budget, e.g. "K8,000/month".', max_length=80)),
                ('preferred_date', models.DateField(blank=True, help_text='Preferred viewing date.', null=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_detail', to='leads.quoterequest')),
            ],
            options={
                'verbose_name': 'real estate detail',
                'verbose_name_plural': 'real estate details',
            },
        ),
    ]
